const mongoose = require('mongoose');

const EnquirySchema = new mongoose.Schema({
    username:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    mobile:{
        type:String,
        required:true
    },
    qualification:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    course:{
        type:String,
        required:true
    },
    gender:{
        type:String,
        required:true
    },
    dob:{
        type:String,
        required:true
    },
    Gmobile:{
        type:String,
        required:true
    },
    passing:{
        type:String,
        required:true
    },
    details:{
        type:String,
        required:true
    }
})
module.exports = mongoose.model('enquirie', EnquirySchema);